#!/bin/bash

mkdir -p ~/.ssh ~/.vim/undo

curl -fsSL https://github.com/b3n4kh.keys >> ~/.ssh/authorized_keys

sort -u -o ~/.ssh/authorized_keys ~/.ssh/authorized_keys


install_via_dnf () {
  sudo dnf install vim direnv tmux git
}

install_via_apt () {
  sudo apt update
  sudo apt install vim direnv tmux git
}


command -v dnf && install_via_dnf

command -v apt && install_via_apt

echo "PS1='\[\e[0;31m\]\u\[\e[0;32m\]@\[\e[0;31m\]\h\[\e[m\] \[\e[0;34m\]\W\[\e[m\] \[\e[0;31m\]\$\[\e[m\] '" | sudo tee /etc/profile.d/prompt.sh
