#!/bin/bash

mkdir -p ~/.ssh ~/.vim/undo

curl -fsSL https://github.com/b3n4kh.keys >> ~/.ssh/authorized_keys

sort -u -o ~/.ssh/authorized_keys ~/.ssh/authorized_keys


install_via_dnf () {
  sudo dnf install vim direnv tmux git
}

install_via_apt () {
  sudo apt update
  sudo apt install vim direnv tmux git
}


command -v dnf && install_via_dnf

command -v apt && install_via_apt

git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt

